name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v3  # Updated to v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the scanner
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}  # Passing the secret as an environment variable
        TARGETS: '192.168.126.132,192.168.126.133'  # Provide the target hosts as an environment variable
      run: |
        python sentinel_scanner/vulnerability.py
        python main.py
